[project]
authors = ["Hossein Ghorbanfekr <hgh.comphys@gmail.com>"]
channels = ["conda-forge"]
description = "Implementing Linear molecular dynamics from scratch"
name = "linear-md"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numba = ">=0.63.1,<0.64"
scalene = ">=1.5.51,<2"
ase = ">=3.27.0,<4"
pandas = ">=2.3.3,<3"

[pypi-dependencies]
py-cpuinfo = "*"
